// angular-app/src/app/hacker-news-list/hacker-news-list.component.ts
import { Component } from '@angular/core';
import { HackerNewsService } from './hacker-news.service';
import { Observable } from 'rxjs';
import { Story } from 'model';
import { map } from 'rxjs/operators';

@Component({
  selector: 'hacker-news-list',
  template: `
    <p>hacker-news-list</p>
    <p>loading: {{ isLoading | async }}</p>
    <!--<input [value]="searchText | async" (change)="handleSearchTextChange($event)" />-->
    <input [ngModel]="searchText | async" (ngModelChange)="handleSearchTextChange($event)" />
    <ul>
      <li *ngFor="let story of stories | async">
        <p>{{ story.title }}</p>
      </li>
    </ul>
  `,
  styleUrls: ['./hacker-news-list.component.css'],
  providers: [HackerNewsService],
})
export class HackerNewsListComponent {

  stories: Observable<Story[]>;
  searchText: Observable<string>;
  isLoading: Observable<string>;

  constructor(private service: HackerNewsService) {
    const { newsList, searchText, loading } = service.model;
    this.stories = newsList as any;
    this.searchText = searchText as any;
    this.isLoading = loading.pipe(
      map(l => l ? 'true' : 'false') as any
    ) as any;
  }

  handleSearchTextChange(text: string) {
    this.service.model.changeSearchText(text);
  }

}

// react-app/src/HackerNewsList/index.tsx
import * as React from 'react';
import { Story } from 'model';
import { model } from './model';

interface Props {}

interface State {
  searchText: string;
  newsList: Story[];
  loading: boolean;
}

class HackerNewsList extends React.Component<Props, State> {
  constructor(props: Props) {
    super(props);
    this.state = {
      searchText: '',
      newsList: [],
      loading: false,
    };
  }

  componentWillMount() {
    const { searchText, newsList, loading } = model;
    
    searchText.subscribe(searchText => this.setState({ searchText }));
    newsList.subscribe(newsList => this.setState({ newsList }));
    loading.subscribe(loading => this.setState({ loading }));
  }

  handleInputChange: React.ReactEventHandler<HTMLInputElement> = ev => {
    const text = ev.currentTarget.value;
    model.changeSearchText(text);
  }

  public render() {
    const { searchText, newsList, loading } = this.state;
    return (
      <div>
        hacker news list
        <p>loading: {loading ? 'true' : 'false'}</p>
        <input value={searchText} onChange={this.handleInputChange} />
        <pre><code>{JSON.stringify(newsList.map(n => n.title), null, 2)}</code></pre>
        <pre><code>{JSON.stringify(newsList, null, 2)}</code></pre>
      </div>
    );
  }
}

export default HackerNewsList;
